### ISSUE TITLE
In what schedule do the different log files rotate?

### ISSUE THREAD

**Issue by sarukuku** [bond-agency/docker-wpbp#11]
- Nginx?
- MariaDB?
- Other system logs?

Gustave seems to gather nginx logs for eternity and just making those single log files larger and larger. We don't want to end up this happening in each of our containers separately so that's why I'm asking.

**Comment by roopemerikukka** [comment]
Logs are all streamed to stdout/stderr and the host machine needs to do the log rotation.

**Comment by roopemerikukka** [comment]
Apparently I was wrong with this and we can define the logging options within the compose file: https://docs.docker.com/compose/compose-file/#logging
