### ISSUE TITLE
Empty www-cache folder automatically when the start script is run

### ISSUE THREAD

**Issue by sarukuku** [bond-agency/docker-wpbp#9]
Currently we don't have this. It would probably be good to test that the disk clean option of the nginx helper wp plugin also works with this new docker setup.

**Comment by roopemerikukka** [comment]
This can be archieved in a same way as [reloading nginx configuration](https://github.com/bond-agency/docker-wpbp/commit/eb1688155a0e88b2ba9e031a572f79db88ddbb78). The working command is:

```bash
docker-compose exec --user=www-data wordpress bash -c "wp nginx-helper purge-all"
```

The problem with above is that there might not be `nginx-helper` plugin installed so maybe we should instead just clear the whole cache folder. Then it wouldn't be tied up to single WordPress plugin. This could be archieved with:

```bash
docker-compose exec wordpress bash -c "rm -rf ../cache/*"
```

**Comment by sarukuku** [comment]
We'll need to add an example purge.sh script to this repo and document its usage.
